---
#mysql pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo

---
# mysql mongodb analyze pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql-analyze-mongo-pod
  labels:
    app: mysql-analyze-mongo-pod
spec:
  volumes:
    - name: mysql-data
      persistentVolumeClaim:   
        claimName: mysql-pvc
  containers:
    - name: analyze
      image: us.gcr.io/app-368216/cluster-1/analyze
      ports:
        - containerPort: 8092
    - name: mysql
      image: us.gcr.io/app-368216/cluster-1/mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: "/var/lib/mysql"
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017