---
# mysql mongodb analyze pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql-analyze-mongo-pod
  labels:
    app: mysql-analyze-mongo-pod
spec:
  volumes:
    - name: mysql-pv
      persistentVolumeClaim:   
        claimName: mysql-pvc
    - name: mongo-pv
      persistentVolumeClaim:   
        claimName: mongo-pvc
  initContainers:
    - name: chmod-er
      image: busybox:latest
      command:
      - /bin/chown
      - -R
      - "1000"  # or whatever the mongo UID is, use string "1000" not 1000 due to yaml
      - /data/db
      volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
  containers:
    - name: analyze
      image: us.gcr.io/app-368216/cluster-1/analyze
      ports:
        - containerPort: 8092
    - name: mysql
      image: us.gcr.io/app-368216/cluster-1/mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
    - name: mongodb
      image: us.gcr.io/app-368216/cluster-1/mongodb
      ports:
        - containerPort: 27017