apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-sv-backend-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-sv-backend-dep
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20