apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-dep
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50