# ---
# #mysql pv
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
#   labels:
#     name: mysql-pv
# spec:
#   capacity:
#     storage: 5Gi
#   storageClassName: standard
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /var/lib/mysql
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: mysql-pvc
# spec:
#   storageClassName: mysql-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

---
#mysql pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  storageClassName: mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # selector:
  #   matchLabels:
  #     name: mysql-pv