apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: analyze
      image: us.gcr.io/app-368216/cluster-1/analyze
      ports:
        - containerPort: 8092
    - name: mysql
      image: us.gcr.io/app-368216/cluster-1/mysql
      ports:
        - containerPort: 3306
    - name: mysqlsv
      image: us.gcr.io/app-368216/cluster-1/mysqlsv
      ports:
        - containerPort: 8090
    - name: auth
      image: us.gcr.io/app-368216/cluster-1/auth
      ports:
        - containerPort: 8080
    - name: mongodb
      image: us.gcr.io/app-368216/cluster-1/mongodb
      ports:
        - containerPort: 27017