apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: enterdata
      image: us.gcr.io/app-368216/cluster-1/enterdata
      ports:
        - containerPort: 8091
    - name: showdata
      image: us.gcr.io/app-368216/cluster-1/showdata
      ports:
        - containerPort: 3000