apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rp
  labels:
    app: frontend-rp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-rp
  template:
    metadata:
      labels:
        app: frontend-rp
    spec: 
      containers:
      - name: enterdata
        image: bennyjiang/enterdata
        ports:
          - containerPort: 8091
      - name: showdata
        image: bennyjiang/showdata
        ports:
          - containerPort: 3000